---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vaultwarden-credentials-secret
    template:
      data:
        VAULT_DB_URL: "{{ .VAULT_DB_URL }}"
        admin-token: "{{ .VAULT_ADMIN_TOKEN }}"
        push-id: "{{ .PUSH_ID }}"
        push-key: "{{ .PUSH_KEY }}"
  dataFrom:
    - extract:
        key: vaultwarden
