---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app netboot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      netboot:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: 0.7.6-nbxyz6@sha256:d39d956fb5afbfab01f450eb09a88cfdf10c94245fae07e91e4db3acd1681e16
            env:
              TZ: Europe/Moscow
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G
    # defaultPodOptions:
    #   securityContext:
        # runAsNonRoot: false
        # runAsUser: 1000
        # runAsGroup: 1000
        # fsGroup: 1000
        # fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
      web:
        enabled: true
        primary: false
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.130.115
        controller: *app
        ports:
          web:
            enabled: true
            primary: false
            port: 80
            targetPort: 80
            protocol: HTTP
      tftp:
        enabled: true
        primary: false
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.130.116
        ports:
          tftp:
            enabled: true
            primary: false
            port: 69
            targetPort: 69
            protocol: UDP
    route:
      app:
        hostnames: ["boot.astrateam.net"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: netboot-app
                port: 3000
    persistence:
      config:
        enabled: true
        existingClaim: *app
      assets:
        enabled: true
        type: nfs
        server: ivn-nas1.astrateam.net
        path: "/volume1/Netboot"
        advancedMounts:
          netboot:
            app:
              - subPath: assets
                path: /assets
