---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app netboot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      netboot:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostNetwork: true
        containers:
          app:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: 0.7.5-nbxyz6@sha256:ff8202d8ee4022d063864458d9ed355040a0492542d893a390a73a07a9e921b9
            # env:
            #   PORT: &port "8080"
            #   NC_JWT_EXPIRES_IN: 48h
            #   NC_S3_REGION: us-east-1
            #   NC_PUBLIC_URL: "https://nocodb.astrateam.net"
            #   NC_REDIS_URL: redis://nocodb-dragonfly.database.svc.cluster.local:6379
            #   NC_DISABLE_TELE: "true"
            #   NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/global-bundle.pem"
            #   NC_INVITE_ONLY_SIGNUP: "true"
            # envFrom:
            #   - secretRef:
            #         name: nocodb-secret
            # # securityContext:
            # #   allowPrivilegeEscalation: false
            # #   readOnlyRootFilesystem: true
            # #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
      web:
        enabled: true
        primary: false
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.130.115
        controller: *app
        ports:
          web:
            enabled: true
            primary: false
            port: 80
            targetPort: 3000
            protocol: HTTP
      tftp:
        enabled: true
        primary: false
        controller: *app
        type: NodePort
        ports:
          tftp:
            enabled: true
            primary: false
            port: 69
            targetPort: 69
            protocol: UDP
    route:
      app:
        hostnames: ["boot.astrateam.net"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: 3000
    persistence:
      config:
        enabled: true
        existingClaim: *app
      assets:
        enabled: true
        type: emptyDir
