---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conf-storage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: conf-storage-secret
    template:
      data:
        credentials: |
          [default]
          aws_access_key_id={{ .S3_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .S3_SECRET_ACCESS_KEY }}
  dataFrom:
    - extract:
        key: confluence

---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: confdb-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: confdb-credentials-secret
    template:
      data:
        CONF_DB_USERNAME: "{{ .CONF_DB_USERNAME }}"
        CONF_DBUSER_PASSWORD: "{{ .CONF_DBUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: confluence

## VOLSYNC

---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "confluence-shared-home"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "confluence-shared-home-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/confluence-shared-home"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template

---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "confluence-local-home"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "confluence-local-home-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/confluence-local-home"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "confluence-syncrhony-home"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "confluence-syncrhony-home-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/confluence-syncrhony-home"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "confluence-opensearch"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "confluence-opensearch-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/confluence-opensearch"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
