---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: confluence
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.0
  url: oci://ghcr.io/astrateam-net/oci-charts/confluence
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/astrateam-net/oci-charts.*$"
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: confluence
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: confluence
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: confluence
    replicaCount: 1
    image:
      repository:  ghcr.io/astrateam-net/wiki
      pullPolicy: IfNotPresent
      tag: 9.3.2@sha256:f4c591307a64c59627ccb52f59e1955f88b53abc3511b0b95b5d10039d5d13d8
    database:
      type: postgresql
      url: "jdbc:postgresql://10.1.125.55:5000/confdbprod"
      driver: org.postgresql.Driver
      credentials:
        secretName: confdb-credentials-secret
        usernameSecretKey: CONF_DB_USERNAME
        passwordSecretKey: CONF_DBUSER_PASSWORD
    volumes:
      localHome:
        customVolume:
          persistentVolumeClaim:
            claimName: "confluence-local-home"
      sharedHome:
        customVolume:
          persistentVolumeClaim:
            claimName: "confuence-shared-home"
        nfsPermissionFixer:
          enabled: false
      synchronyHome:
        customVolume:
          persistentVolumeClaim:
            claimName: "confluence-syncrhony-home"
    confluence:
      useHelmReleaseNameAsContainerName: false
      readinessProbe:
        enabled: true
      resources:
        jvm:
          maxHeap: "2g"
          minHeap: "2g"
      postStart:
        command: |
          update-ca-certificates
      s3AttachmentsStorage:
        bucketName: confluence
        bucketRegion: us-east-1
        endpointOverride: https://s3.astrateam.net
      additionalJvmArgs:
        - "-Dupm.plugin.upload.enabled=true"
      additionalCertificates:
        secretName: root-ca
    synchrony:
      enabled: true
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-03
    additionalFiles:
      - name: conf-storage-secret
        type: secret
        key: credentials
        mountPath: /var/atlassian/application-data/confluence/.aws/
      - name: minio-ca
        type: secret
        key: minio.crt
        mountPath: /usr/local/share/ca-certificates/minio.crt
        readOnly: true
    opensearch:
      enabled: true
      credentials:
        createSecret: false
        existingSecretRef: opensearch-initial-password
      name:
      persistence:
        enabled: false
        storageClass: ceph-block
        size: 10Gi
      extraVolumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: confluence-opensearch
      extraVolumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
    # nodeSelector:
    #   kubernetes.io/hostname: k8s-02
