---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-local-home
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "confluence-local-home-dst"
  resources:
    requests:
      storage: 25Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confuence-shared-home
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "confuence-shared-home-dst"
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-syncrhony-home
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "confluence-syncrhony-home-dst"
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: confluence-opensearch
# spec:
#   accessModes: ["ReadWriteOnce"]
#   dataSourceRef:
#     kind: ReplicationDestination
#     apiGroup: volsync.backube
#     name: "confluence-opensearch-dst"
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: ceph-block
