---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ai-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ai-credentials-secret
    template:
      data:
        PAPERLESS_API_TOKEN: '{{ .PAPERLESS_API_TOKEN }}'
        PAPERLESS_USERNAME: '{{ .PAPERLESS_ADMIN_USER }}'
        OPENAI_API_KEY: '{{ .PPR_OPENAI_API_KEY }}'
  dataFrom:
    - extract:
        key: paperless
    # - extract:
    #     key: openai
