---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ai
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      paperless-ai:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/clusterzx/paperless-ai
              tag: 2.7.6@sha256:c8ec15eccd08fe550d227297baf85130d375215196b40d2a9dd60fa62a41573e
            env:
              TZ: Europe/Moscow
              PROCESS_PREDEFINED_DOCUMENTS: true
              AI_PROVIDER: openai
              OLLAMA_MODEL: gpt-4o-mini
              PAPERLESS_API_URL: https://dms.astrateam.net/api
              SCAN_INTERVAL: "*/30 * * * *"
              TAGS: AI
            envFrom:
              - secretRef:
                  name: paperless-ai-credentials-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: paperless-ai
        ports:
          http:
            port: &port 3000

    route:
      app:
        hostnames: ["dms-ai.astrateam.net"]
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: si-paperlessngx
          gethomepage.dev/name: Paperless AI
          gethomepage.dev/group: AI
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      cache:
        type: emptyDir
        globalMounts:
          - path: /app/public/images
      home:
        type: emptyDir
        globalMounts:
          - path: /home/node/.pm2
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      openai:
        type: emptyDir
        globalMounts:
          - path: /app/OPENAPI
