---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app redis-api
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/dragonfly
    # - ../../../../components/volsync
  dependsOn:
    - name: dragonfly
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/default/redis-api/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CACHE_CAPACITY: 8Gi
      VOLSYNC_CAPACITY: 8Gi
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
