---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-backup-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "mysql-db-backup-pvc"
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-block
