# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-db-backup"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-db-backup-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/${APP}-db-backup"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-db-secret"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-mysql-secret"
    template:
      data:
        rootUser: "{{ .MYSQL_ROOT_USER }}"
        rootHost: "{{ .MYSQL_ROOT_HOST }}"
        rootPassword: "{{ .MYSQL_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: mysql-innodbcluster
