---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: microsoft-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.16.1
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app microsoft-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: microsoft-dns
  install:
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    provider:
      name: rfc2136
      webhook:
        readinessProbe: null
    # env:
    #   - name: &name RFC2136_KERBEROS_USERNAME
    #     valueFrom:
    #       secretKeyRef:
    #         name: &secret rfc2136-keys-secret
    #         key: *name
    #   - name: &name RFC2136_KERBEROS_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: *secret
    #         key: *name
    # extraVolumeMounts:
    #   - name: kerberos-config-volume
    #     mountPath: /etc/krb5.conf
    #     subPath: krb5.conf
    # extraVolumes:
    #   - name: kerberos-config-volume
    #     configMap:
    #       name: krb5.conf
    #       defaultMode: 420
    extraArgs:
      # - --rfc2136-gss-tsig
      # - --rfc2136-kerberos-username=$(RFC2136_KERBEROS_USERNAME)
      # - --rfc2136-kerberos-password=$(RFC2136_KERBEROS_PASSWORD)
      # - --rfc2136-kerberos-realm=ASTRATEAM.NET
      - --rfc2136-zone=astrateam.net
      - --rfc2136-host=IVN-DC01.astrateam.net
      - --rfc2136-host=IVN-DC02.astrateam.net
      - --rfc2136-load-balancing-strategy=round-robin
      - --rfc2136-port=53
      - --rfc2136-tsig-axfr
      - --rfc2136-insecure

    triggerLoopOnEvent: true
    policy: sync
    sources: ["crd", "gateway-httproute", "service"]
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["astrateam.net"]
    logLevel: debug
    serviceMonitor:
      enabled: true
    # podAnnotations:
    #   secret.reloader.stakater.com/reload: *secret
