---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./vaultwarden/ks.yaml
  - ./homepage/ks.yaml
  - ./n8n/ks.yaml
  # - ./paperless/ks.yaml
  - ./emqx/ks.yaml
  - ./home-assistant/ks.yaml
