---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nocodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      nocodb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nocodb/nocodb
              tag: 0.265.1@sha256:8fd57018accf775fb5390392910e4b0ef6bb154f17c5732b478eb76c40ee8d1e
            env:
              PORT: &port "8080"
              NC_JWT_EXPIRES_IN: 48h
              NC_S3_REGION: us-east-1
              NC_PUBLIC_URL: "https://nocodb.astrateam.net"
              NC_REDIS_URL: redis://nocodb-dragonfly.database.svc.cluster.local:6379
              NC_DISABLE_TELE: "true"
              NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/global-bundle.pem"
              NC_INVITE_ONLY_SIGNUP: "true"
            envFrom:
              - secretRef:
                    name: nocodb-secret
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: "${APP_UID}"
        runAsGroup: "${APP_GID}"
        fsGroup: "${APP_GID}"
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65568
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.astrateam.net"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          nocodb:
            app:
              - path: /usr/app/data

      ca-bundle:
        enabled: true
        type: secret
        name: nocodb-secret
        advancedMounts:
          nocodb:
            app:
              - path: /usr/local/share/ca-certificates/global-bundle.pem
                subPath: sslrootcert
