---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-storage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jira-storage-secret
    template:
      data:
        credentials: |
          [default]
          aws_access_key_id={{ .S3_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .S3_SECRET_ACCESS_KEY }}
  dataFrom:
    - extract:
        key: jia

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jiradb-credentials-secret
    template:
      data:
        JIRA_DB_USER: "{{ .JIRA_DB_USER }}"
        JIRA_DB_PASSWORD: "{{ .JIRA_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: jira
