---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jira
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: jira.png
    gethomepage.dev/name: Jira
    gethomepage.dev/group: Главная
    gethomepage.dev/description: Система управления проектами
spec:
  hostnames: ["jira.astrateam.net"]
  parentRefs:
    - name: external
      namespace: network
      sectionName: https
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: jira
          namespace: atlassian
          port: 80
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jira-help-path-rewrite
spec:
  hostnames:
    - help.astrateam.net
  parentRefs:
    - name: external       # Change if your Gateway has a different name
      namespace: network  # Change if your Gateway is in a different namespace
      sectionName: https  # This matches your TLS listener
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /servicedesk/customer/portal/1
      backendRefs:
        - name: jira
          namespace: atlassian
          port: 80
