---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "jira-local-home"
spec:
  sourcePVC: "jira-local-home"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 14
    repository: "jira-local-home-volsync-secret"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: 25Gi
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "jira-shared-home"
spec:
  sourcePVC: "jira-shared-home"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 14
    repository: "jira-shared-home-volsync-secret"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: 5Gi
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
