---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flowise
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.0
  url: oci://ghcr.io/astrateam-net/oci-charts/flowise
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/astrateam-net/oci-charts.*$"
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flowise
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flowise
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    updateStrategy:
      type: Recreate
    image:
      registry: docker.io
      repository: flowiseai/flowise
      tag: 3.0.2
      pullPolicy: IfNotPresent
    serviceAccount:
      create: true
    containerPorts:
      ## @param containerPorts.http Container port for HTTP
      http: 3000
    service:
      type: ClusterIP
      externalTrafficPolicy: Cluster
      ports:
        http: 3000
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    extraEnvVars:
      - name: DATABASE_SSL
        value: "true"
      - name: DATABASE_TYPE
        value: "postgres"
      - name: DATABASE_HOST
        value: "10.1.125.55"
      - name: DATABASE_PORT
        value: "5000"
      - name: DATABASE_NAME
        value: "flowisedbprod"
      - name: DATABASE_USER
        value: "flowisedb_user"
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flowdb-credentials-secret
            key: FLOWISE_DBUSER_PASSWORD
      - name: DATABASE_SSL_KEY_BASE64
        valueFrom:
          secretKeyRef:
            name: flowdb-credentials-secret
            key: PG_CRT
      - name: FLOWISE_USERNAME
        valueFrom:
          secretKeyRef:
            name: flowise-credentials-secret
            key: FLOWISE_USER
      - name: FLOWISE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flowise-credentials-secret
            key: FLOWISE_PASSWORD
    extraEnvVarsSecret: flowdb-credentials-secret
    # extraVolumes:
    #   - name: pg-ca
    #     secret:
    #       secretName: flowdb-credentials-secret
    #       items:
    #         - key: PG_CRT
    #           path: my-postgres-ca.crt
    # extraVolumeMounts:
    #   - name: pg-ca
    #     mountPath: /usr/local/share/ca-certificates/my-postgres-ca.crt
    #     subPath: my-postgres-ca.crt
    #     readOnly: true
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 3Gi
      storageClass: ceph-block
    # config:
    #   username: "flowise"
    # existingSecret: "flowise-credentials-secret"
    # existingSecretKeyPassword: FLOWISE_PASSWORD
    externalPostgresql:
      ## @param externalPostgresql.enabled Whether to use an external PostgreSQL
      enabled: false
      host: 10.1.125.55
      port: 5000
      username: flowisedb_user
      existingSecret: "flowdb-credentials-secret"
      existingSecretKeyPassword: FLOWISE_DBUSER_PASSWORD
      database: flowisedbprod
