---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app affine
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      affine:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          migration:
            image:
              repository: ghcr.io/toeverything/affine-graphql
              tag: stable
            command:
              - sh
              - -c
              - |
                node --no-deprecation --loader ts-node/esm/transpile-only scripts/self-host-predeploy
            env:
              NODE_ENV: production
              REDIS_SERVER_HOST: affine-dragonfly.default.svc.cluster.local
              REDIS_SERVER_PORT: "6379"
              REDIS_SERVER_DATABASE: "0"
            envFrom:
              - secretRef:
                  name: affine-secret

        containers:
          app:
            image:
              repository: ghcr.io/toeverything/affine-graphql
              tag: stable
            env:
              NODE_ENV: production
              # Redis configuration
              REDIS_SERVER_HOST: affine-dragonfly.default.svc.cluster.local
              REDIS_SERVER_PORT: "6379"
              REDIS_SERVER_DATABASE: "0"
              # Server configuration
              PORT: &port "3010"
              AFFINE_INDEXER_ENABLED: "true"
              # Storage
              DB_DATA_LOCATION: /data/database
              UPLOAD_LOCATION: /data/uploads
              CONFIG_LOCATION: /data/config
            envFrom:
              - secretRef:
                  name: affine-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Productivity
          gethomepage.dev/name: AFFiNE
          gethomepage.dev/icon: affine.png
          gethomepage.dev/description: Knowledge Base & Collaboration
        hostnames: ["affine.astrateam.net"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
