---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: affine
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      affine:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          migration:
            image:
              repository: ghcr.io/toeverything/affine
              tag: stable
            command:
              - sh
              - -c
              - node ./scripts/self-host-predeploy.js
            env:
              - name: REDIS_SERVER_HOST
                value: "affine-dragonfly.default.svc.cluster.local"
              - name: AFFINE_INDEXER_ENABLED
                value: "false"
              - name: NODE_OPTIONS
                value: "--max-old-space-size=4096"
            envFrom:
              - secretRef:
                  name: affine-secret

        containers:
          app:
            image:
              repository: ghcr.io/toeverything/affine
              tag: stable
              pullPolicy: Always
            env:
              - name: REDIS_SERVER_HOST
                value: "affine-dragonfly.default.svc.cluster.local"
              - name: AFFINE_INDEXER_ENABLED
                value: "false"
              - name: NODE_OPTIONS
                value: "--max-old-space-size=4096"
              - name: AFFINE_SERVER_PORT
                value: &port "3010"
              - name: AFFINE_SERVER_HOST
                value: "0.0.0.0"
            envFrom:
              - secretRef:
                  name: affine-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: affine
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["affine.astrateam.net"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: app
                port: *port

    persistence:
      config:
        existingClaim: affine
        globalMounts:
          - path: /root/.affine/config
            subPath: config
      storage:
        existingClaim: affine
        globalMounts:
          - path: /root/.affine/storage
            subPath: storage
