---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app affine
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      affine:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          model-name-fix:
            image:
              repository: ghcr.io/toeverything/affine-graphql
              tag: stable
            command:
              - sh
              - -c
              - |
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/gemini-embedding-001/text-embedding-3-small/g' {} \; &&
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/claude-sonnet-4@20250514/anthropic\/claude-sonnet-4-20250514/g' {} \; &&
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/claude-sonnet-4-5@20250929/anthropic\/claude-sonnet-4-20250514/g' {} \; &&
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/gemini-2\.5-flash/google\/gemini-2.0-flash-exp/g' {} \; &&
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/gpt-4\.1/openai\/gpt-4o/g' {} \; &&
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/gpt-5-mini/openai\/gpt-4o-mini/g' {} \; &&
                find . -name '*.js' -type f -not -path '*/node_modules/*' -exec sed -i 's/gpt-image-1/openai\/gpt-4o/g' {} \; &&
                echo "Model names fixed for OpenRouter compatibility"
          affine-migration:
            image:
              repository: ghcr.io/toeverything/affine-graphql
              tag: stable
            command:
              - sh
              - -c
              - node ./scripts/self-host-predeploy.js
            env:
              AFFINE_INDEXER_ENABLED: "false"
              REDIS_SERVER_HOST: affine-dragonfly.default.svc.cluster.local
              REDIS_SERVER_PORT: "6379"
              REDIS_SERVER_DATABASE: "0"
            envFrom: &envFrom
              - secretRef:
                  name: affine-secret

        containers:
          app:
            image:
              repository: ghcr.io/toeverything/affine-graphql
              tag: stable
            command:
              - node
              - ./dist/main.js
            env:
              NODE_ENV: production
              PORT: &port "3010"
              AFFINE_INDEXER_ENABLED: "false"
              OAUTH_EMAIL_LOGIN: "false"
              REDIS_SERVER_HOST: affine-dragonfly.default.svc.cluster.local
              REDIS_SERVER_PORT: "6379"
              REDIS_SERVER_DATABASE: "0"
              CONFIG_LOCATION: "/root/.affine/config"
            envFrom: *envFrom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Productivity
          gethomepage.dev/name: AFFiNE
          gethomepage.dev/icon: affine.png
          gethomepage.dev/description: Knowledge Base & Collaboration
        hostnames:
          - "affine.astrateam.net"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      app-code:
        type: emptyDir
        advancedMounts:
          affine:
            model-name-fix:
              - path: /app
            affine-migration:
              - path: /app
            app:
              - path: /app
      data:
        existingClaim: *app
        advancedMounts:
          affine:
            app:
              - path: /root/.affine/storage
      config:
        type: secret
        name: affine-config-secret
        advancedMounts:
          affine:
            app:
              - path: /root/.affine/config/config.json
                subPath: config.json
