---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: affine
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: affine.png
    gethomepage.dev/name: AFFiNE
    gethomepage.dev/group: Productivity
    gethomepage.dev/description: Knowledge Base & Collaboration
spec:
  hostnames: ["affine.astrateam.net"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: affine-app
          namespace: default
          port: 3010

