---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app redis-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: redis-api-secret
    template:
      data:
        appsettings.json: |-
          {
            "Serilog": {
              "MinimumLevel": "Information",
              "LevelSwitches": {
                "$controlSwitch": "Information"
              },
              "WriteTo": [
                {
                  "Name": "Seq",
                  "Args": {
                    "serverUrl": "http://localhost:5341",
                    "apiKey": "{{ .REDIS_API_KEY }}",
                    "controlLevelSwitch": "$controlSwitch"
                  }
                },
                {
                  "Name": "Console"
                }
              ]
            },
            "Redis": {
              "ConnectionString": "redis://redis-api-dragonfly.default.svc.cluster.local:6379"
            },
            "Docs": true
          }
  dataFrom:
    - extract:
        key: redis-api

---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-commander
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: redis-commander-secret
    template:
      data:
        # Paperless
        HTTP_USER: "{{ .HTTP_USER }}"
        HTTP_PASSWORD: "{{ .HTTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: redis-api
