---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-api-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: redis-api-config
    kind: ConfigMap
    template:
      data:
        appsettings.json: |-
          {
            "Serilog": {
              "MinimumLevel": "Information",
              "LevelSwitches": {
                "$controlSwitch": "Information"
              },
              "WriteTo": [
                {
                  "Name": "Seq",
                  "Args": {
                    "serverUrl": "http://localhost:5341",
                    "apiKey": "{{ .REDIS_API_KEY }}",
                    "controlLevelSwitch": "$controlSwitch"
                  }
                },
                {
                  "Name": "Console"
                }
              ]
            },
            "Redis": {
              "ConnectionString": "redis://redis-api-dragonfly.default.svc.cluster.local:6379"
            },
            "Docs": true
          }
  dataFrom:
    - extract:
        key: redis-api

