---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redis-api
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    controllers:
      redis-api:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/astrateam-net/rest-api-redis
              tag: 2.15.3@sha256:6fce48ebb9b3252e7cd7fad97644752d8476202c7db081ac5c31b9bada10566f
            volumeMounts:
              - name: appsettings
                mountPath: /app/appsettings.json
                subPath: appsettings.json
        volumes:
          - name: appsettings
            secret:
              secretName: redis-api-secret


    service:
      redis-api:
        controller: *app
        annotations:
          lbipam.cilium.io/ips: 10.1.130.117
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames: ["redisapi.astrateam.net"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
