---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: &app paperless
# spec:
#   refreshInterval: 5m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: onepassword
#   target:
#     name: paperless-secret
#     template:
#       data:
#         # Paperless
#         PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
#         PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
#         PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
#           {"openid_connect":{"APPS":[{"provider_id":"authelia","name":"Authelia","client_id":"{{ .PAPERLESS_OAUTH_CLIENT_ID }}","secret":"{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}","settings":{"server_url":"https://auth.chestr.dev/.well-known/openid-configuration"}}]}}
#   dataFrom:
#     - extract:
#         key: authelia
#     - extract:
#         key: paperless

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-pg
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-pguser-secret
    template:
      data:
        # Paperless
        user: "{{ .PPR_DB_USERNAME }}"
        password: "{{ .PPR_DBUSER_PASSWORD }}"
        host: "{{ .PPR_DB_HOST }}"
        hostport: "{{ .PPR_DB_HOSTPORT }}"
        sslrootcert: "{{ .PPR_DB_SSLROOTCERT }}"
        db: "{{ .PPR_DB_NAME }}"
  dataFrom:
    - extract:
        key: paperless
