---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-pg
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nocodb-secret
    template:
      data:
        # Paperless
        DATABASE_URL: "{{ .NOCODB_DB_STRING }}"
        NC_AUTH_JWT_SECRET: "{{ .NC_AUTH_JWT_SECRET }}"
        NC_S3_ENDPOINT: "{{ .NC_S3_ENDPOINT }}"
        NC_S3_BUCKET_NAME: "{{ .NC_S3_BUCKET_NAME }}"
        # NC_S3_FORCE_PATH_STYLE: "{{ .NC_S3_FORCE_PATH_STYLE }}"
        NC_S3_ACCESS_KEY: "{{ .NC_S3_ACCESS_KEY }}"
        NC_S3_ACCESS_SECRET: "{{ .NC_S3_ACCESS_SECRET }}"
        NC_ADMIN_EMAIL: "{{ .NC_ADMIN_EMAIL }}"
        NC_ADMIN_PASSWORD: "{{ .NC_ADMIN_PASSWORD }}"
        sslrootcert: "{{ .ROOT_CA }}"
  dataFrom:
    - extract:
        key: nocodb
