---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "confluence-shared-home"
spec:
  sourcePVC: "confluence-shared-home"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 14
    repository: "confluence-shared-home-volsync-secret"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: 30Gi
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "local-home-confluence"
spec:
  sourcePVC: "local-home-confluence-0"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 14
    repository: "local-home-confluence-volsync-secret"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: 10Gi
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "opensearch-cluster"
spec:
  sourcePVC: "opensearch-cluster-master-opensearch-cluster-master-0"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 14
    repository: "opensearch-cluster-volsync-secret"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: 10Gi
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "synchrony-home-confluence"
spec:
  sourcePVC: "synchrony-home-confluence-synchrony-0"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 14
    repository: "synchrony-home-confluence-volsync-secret"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheCapacity: 2Gi
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
