---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
spec:
  type: github
  address: https://github.com/astrateam-net/k8s-cluster
  secretRef:
    name: github-status-token-secret
