---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xibo-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: xibo-secret
    template:
      data:
        MYSQL_HOST: "mysql-innodbcluster.database.svc.cluster.local"
        MYSQL_PORT: "6446"
        MYSQL_DATABASE: "xibo-db"
        MYSQL_USER: "{{ .MYSQL_XIBO_USER }}"
        MYSQL_PASSWORD: "{{ .MYSQL_XIBO_PASSWORD }}"
        CMS_QUICK_CHART_URL: "cms-quickchart.media.svc.cluster.local:3400"
        CMS_USAGE_REPORT: "false"
        CMS_SERVER_NAME: xibo.astrateam.net
        CMS_PHP_POST_MAX_SIZE: 4G
        CMS_PHP_UPLOAD_MAX_FILESIZE: 4G
        CMS_PHP_MAX_EXECUTION_TIME: "600"
        CMS_USE_MEMCACHED: "false"
        MEMCACHED_HOST: "xibo-dragonfly.media.svc.cluster.local"
        MEMCACHED_PORT: "11211"
        rootUser: "{{ .MYSQL_ROOT_USER }}"
        rootPassword: "{{ .MYSQL_ROOT_PASSWORD }}"

  dataFrom:
    - extract:
        key: mysql-innodbcluster
    - extract:
        key: xibo
