---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app xibo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: k8s-02
    #   automountServiceAccountToken: false
    #   enableServiceLinks: false
    #   securityContext:
    #     runAsNonRoot: false
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    #     seccompProfile: { type: RuntimeDefault }
    controllers:
      xibo:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/xibosignage/xibo-cms
              tag: release-4.2.3
            env:
              XMR_HOST: xibo-cms-xmr.media.svc.cluster.local
            envFrom:
              - secretRef:
                  name: xibo-secret
            resources:
              limits:
                memory: 1Gi

      cms-xmr:
        containers:
          app:
            image:
              repository: ghcr.io/xibosignage/xibo-xmr
              tag: 1.1
            envFrom:
              - secretRef:
                  name: xibo-secret
            resources:
              limits:
                memory: 265Mi

      cms-quickchart:
        containers:
          app:
            image:
              repository: ianw/quickchart
              tag: v1.8.1@sha256:12e2d442e2db9974f2b310b72fadd4f6d595d0a0bf5480c3d50ef5cb5967ee56
    service:
      xibo:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.130.120
          # lbipam.cilium.io/sharing-key: "xibo-shared"
        ports:
          http:
            port: &port 80
      cms-xmr:
        controller: cms-xmr
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.130.121
          # lbipam.cilium.io/sharing-key: "xibo-shared"
        ports:
          http:
            port: 9505
      cms-quickchart:
        controller: cms-quickchart
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.130.122
          # lbipam.cilium.io/sharing-key: "xibo-shared"
        ports:
          http:
            port: 3400

    route:
      app:
        hostnames: ["xibo.astrateam.net"]
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Xibo
          gethomepage.dev/group: Главная
          gethomepage.dev/description: Digital Signage
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: xibo-xibo
                port: *port


    persistence:
      shared:
        existingClaim: *app
        advancedMounts:
          xibo:
            app:
              - path: /var/www/cms/custom
                subPath: cms/custom
              - path: /var/www/backup
                subPath: backup
              - path: /var/www/cms/web/theme/custom
                subPath: cms/web/theme/custom
              - path: /var/www/cms/library
                subPath: cms/library
              - path: /var/www/cms/web/userscripts
                subPath: cms/web/userscripts
              - path: /var/www/cms/ca-certs
                subPath: cms/ca-certs
