---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app xibo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    controllers:
      xibo:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/xibosignage/xibo-cms
              tag: release-4.2.3@sha256:3db820a540804b854a5b3234026ca5b2c938a5d65dc1145f74e9933529064d19
            env:
              XMR_HOST: cms-xmr.media.svc.cluster.local
          envFrom:
            secretRef:
              name: xibo-secret
          resources:
            limits:
              memory: 1Gi

      cms-xmr:
        containers:
          app:
            image:
              repository: ghcr.io/xibosignage/xibo-xmr
              tag: 1.1@sha256:b0216efd38bb892e3bbf85fcdcaa91246940faaa4678b639665b3d1d53cfc5c2
          envFrom:
            secretRef:
              name: xibo-secret
          resources:
            limits:
              memory: 265Mi

      cms-quickchart:
        containers:
          app:
            image:
              repository: ianw/quickchart
              tag: v1.8.1@sha256:12e2d442e2db9974f2b310b72fadd4f6d595d0a0bf5480c3d50ef5cb5967ee56
    service:
      xibo:
        controller: *app
        ports:
          http:
            port: &port 80
      cms-xmr:
        controller: cms-xmr
        ports:
          http:
            port: 9505
      cms-quickchart:
        controller: cms-quickchart
        ports:
          http:
            port: 3400



    route:
      app:
        hostnames: ["xibo.astrateam.net"]
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Xibo
          gethomepage.dev/group: Главная
          gethomepage.dev/description: Digital Signage
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          xibo:
            app:
              - path: /var/www/cms/custom:Z
                subPath: cms/custom
              - path: /var/www/backup:Z
                subPath: backup
              - path: /var/www/cms/web/theme/custom:Z
                subPath: cms/web/theme/custom
              - path: /var/www/cms/library:Z
                subPath: cms/library
              - path: /var/www/cms/web/userscripts:Z
                subPath: cms/web/userscripts
              - path: /var/www/cms/ca-certs:Z
                subPath: cms/ca-certs
