---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: add-storageclass-to-pvc
spec:
  policyName: add-storageclass-to-pvc
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/mutatingadmissionpolicy-admissionregistration-v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: add-storageclass-to-pvc
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["persistentvolumeclaims"]
  matchConditions:
    - name: is-from-mysql-operator
      expression: object.metadata.labels["app.kubernetes.io/managed-by"] == "mysql-operator"
    - name: is-in-media-ns
      expression: request.namespace == "media"
    - name: no-storageclass
      expression: object.spec.storageClassName == null || object.spec.storageClassName == ""
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          [
            JSONPatch{
              op: "add",
              path: "/spec/storageClassName",
              value: "openebs-hostpath"
            }
          ]

