---
apiVersion: v1
kind: Service
metadata:
  name: xibo-dragonfly-ex
spec:
  selector:
    app: xibo-dragonfly
    app.kubernetes.io/name: dragonfly
    role: master
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: memcached
      port: 11211
      targetPort: 11211
      protocol: TCP
  type: ClusterIP
