---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jirasoft-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jirasoftdb-credentials-secret
    template:
      data:
        JIRA_DB_USERNAME: "{{ .JIRA_DB_USERNAME }}"
        JIRA_DBUSER_PASSWORD: "{{ .JIRA_DBUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: jira

---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "jirasoft-local-home"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "jirasoft-local-home-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/jirasoft-local-home"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "jirasoft-shared-home"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "jirasoft-shared-home-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "/repository/jirasoft-shared-home"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
