---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jirasoft-local-home
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "jirasoft-local-home-dst"
  resources:
    requests:
      storage: 25Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jirasoft-shared-home
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "jirasoft-shared-home-dst"
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
