---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jiradev-local-home
spec:
  accessModes: ["ReadWriteOnce"]
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "jira-local-home-dst"
  resources:
    requests:
      storage: 25Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jiradev-shared-home
spec:
  accessModes: ["ReadWriteOnce"]
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "jira-shared-home-dst"
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block