---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: "pve03=10.1.115.13:3300"
  mapping: "{}"
  maxMonId: "2"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-cluster-user-command
  namespace: rook-ceph
data:
  args: ""
